version: "3"

services:
  postgres:
    image: "bitnami/postgresql"
    restart: always
    ports:
      - "5434:5434"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=quiz.io
    volumes:
      - "postgresql_data:/bitnami/postgres"
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge

volumes:
  postgresql_data:
    driver: local
